apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanter-deployment
  labels:
    app: nanter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanter
  template:
    metadata:
      labels:
        app: nanter
    spec:
      containers:
      - name: nanter-container
        image: gurghet/nano-backend:0.9.0
        ports:
          - containerPort: 9000
        env:
          - name: HTTP_PORT
            value: "9000"
          - name: DB_PWD
            value: "t6KDX2XQJS"
          - name: DB_USER
            value: "postgres"
          - name: DB_URI
            value: "jdbc:postgresql://postgres-nano-postgresql:5432/postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: nanter-service
spec:
  selector:
    app: nanter
  type: LoadBalancer
  ports:
    - port: 9000
